const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photo=id=>PHOTOS.find(p=>p.id===id);
const filmLink=f=>f.imdb?`https://www.imdb.com/title/${f.imdb}/`:`https://www.imdb.com/find/?q=${encodeURIComponent(f.title+' '+f.year)}&s=tt`;
const person=n=>`<a href="https://www.imdb.com/find/?q=${encodeURIComponent(n)}&s=nm" target="_blank" rel="noopener">${esc(n)}</a>`;
const image=l=>photo(l.id)?`<img src="assets/${l.id}.jpg" alt="${esc(l.id==='matera'?'Matera city view':l.name)} ,  real location photograph" loading="lazy">`:`<span class="place-plaque" aria-label="${esc(l.name)}"><span>${esc(l.scope.toUpperCase())} REFERENCE</span><strong>${esc(l.city)}</strong><small>${l.lat.toFixed(2)}°, ${l.lon.toFixed(2)}°</small></span>`;
let category='',query='',country='',mode='globe',selected='glenfinnan',filmFilter='',world=null,rotation=[-12,-24,0],zoom=1;
const collections=[...new Set(FILMS.flatMap(f=>f.collections))].sort((a,b)=>a.localeCompare(b));
const categories=['All locations','007','Marvel','Mission: Impossible','Christopher Nolan','Steven Spielberg','George Lucas'];
function matchFilm(f){return (!category||f.collections.includes(category))&&(!filmFilter||f.id===filmFilter)&&(!query||[f.title,f.year,f.director,...f.cast,...f.collections].join(' ').toLowerCase().includes(query.toLowerCase()))}
function matchLocation(l){return (!country||l.country===country)&&l.films.some(f=>(!category||f.collections.includes(category))&&(!filmFilter||f.id===filmFilter)&&(!query||[l.name,l.city,l.country,f.title,f.year,f.director,...f.cast,...f.collections].join(' ').toLowerCase().includes(query.toLowerCase())))}
function filtered(){return LOCATIONS.filter(matchLocation)}
function filteredFilms(){return FILMS.filter(f=>(!category||f.collections.includes(category))&&(!filmFilter||f.id===filmFilter)&&(!country||f.locationIds.some(id=>LOCATIONS.find(l=>l.id===id)?.country===country))&&(!query||[f.title,f.year,f.director,...f.cast,...f.collections,...f.locationIds.flatMap(id=>{const l=LOCATIONS.find(l=>l.id===id);return l?[l.name,l.city,l.country]:[]})].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>a.year-b.year||a.title.localeCompare(b.title))}
function render(){const list=filtered();$('collection').value=category;$('chips').innerHTML=categories.map((c,i)=>`<button class="chip ${category===(i?c:'')?'active':''}" data-category="${esc(i?c:'')}">${esc(c)}</button>`).join('');$('resultCount').textContent=`${list.length} locations`;$('mapCount').textContent=`${list.length} places to discover`;$('resultsTitle').textContent=(FILMS.find(f=>f.id===filmFilter)?.title)||country||category||'On the map';$('resultList').innerHTML=list.length?list.map(l=>{const fs=l.films.filter(f=>(!category||f.collections.includes(category))&&(!filmFilter||f.id===filmFilter));const first=fs.find(matchFilm)||fs[0];return `<button class="result-card" data-location="${l.id}">${image(l)}<span class="result-text"><small>${esc(l.tag)}</small><h3>${esc(l.name)}</h3><p>${esc(l.city)} · ${esc(l.country)}</p><p class="film-name">${esc(first.title)} <span>${first.year}</span>${fs.length>1?` <span>+${fs.length-1}</span>`:''}</p></span><span class="chev">›</span></button>`}).join(''):'<p class="empty">No mapped locations match these filters. Browse movies for animated films and titles awaiting location research.</p>';renderMovies();drawGlobe();}
$('country').innerHTML+=[...new Set(LOCATIONS.map(l=>l.country))].sort().map(c=>`<option>${esc(c)}</option>`).join('');
$('collection').innerHTML='<option value="">All collections</option>'+collections.map(c=>`<option>${esc(c)}</option>`).join('');
function chooseCategory(c){category=c;filmFilter='';render()}
$('chips').onclick=e=>{const b=e.target.closest('[data-category]');if(b)chooseCategory(b.dataset.category)};
$('collection').onchange=e=>chooseCategory(e.target.value);
$('search').oninput=e=>{query=e.target.value;filmFilter='';render()};$('country').onchange=e=>{country=e.target.value;filmFilter='';render()};
function reset(){category='';query='';country='';filmFilter='';$('search').value='';$('country').value='';render()}$('reset').onclick=reset;
function setMode(m){mode=m;$('workspace').hidden=m!=='globe';$('movieBrowser').hidden=m!=='movies';$('exploreNav').classList.toggle('active',m==='globe');$('moviesNav').classList.toggle('active',m==='movies');if(m==='globe')drawGlobe()}
$('exploreNav').onclick=()=>setMode('globe');$('moviesNav').onclick=()=>setMode('movies');
function renderMovies(){const films=filteredFilms();$('movieCount').textContent=`${films.length} films`;$('movieGrid').innerHTML=films.length?films.map(f=>{const places=LOCATIONS.filter(l=>f.locationIds.includes(l.id)&&(!country||l.country===country));return `<button class="movie-card" data-film="${f.id}">${places.length?image(places.find(l=>photo(l.id))||places[0]):`<span class="place-plaque"><span>${esc(f.kind.toUpperCase())}</span><strong>${f.year}</strong><small>${f.kind==='Animated film'?'No physical filming pin':'Location research pending'}</small></span>`}<div><div class="eyebrow">${f.year} · ${places.length?places.length+' '+(places.length===1?'MAPPED PLACE':'MAPPED PLACES'):esc(f.kind.toUpperCase())}</div><h3>${esc(f.title)}</h3><p>${esc(f.director||f.kind)}</p><p class="collection-name">${esc(f.collections.join(' · '))}</p></div></button>`}).join(''):'<p class="empty">No films match. Reset the filters to explore the catalogue.</p>';}
function pivotFilm(id){const f=FILMS.find(f=>f.id===id);if(!f)return;category='';country='';query='';filmFilter=id;$('country').value='';$('search').value='';setMode('globe');render();const l=filtered()[0];if(l){rotation=[-l.lon,-l.lat,0];drawGlobe()}$('workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function openFilm(id){const f=FILMS.find(f=>f.id===id);if(!f)return;const places=LOCATIONS.filter(l=>f.locationIds.includes(l.id));$('detailBody').innerHTML=`<div class="detail-content film-profile"><div class="eyebrow">${esc(f.collections.join(' · '))}</div><h2>${esc(f.title)}</h2><div class="location-line">${f.year} · ${esc(f.kind)}</div><p>Director: ${person(f.director)}</p>${f.cast.length?`<p class="people">Cast: ${f.cast.map(person).join(' · ')}</p>`:''}<p>${places.length?`${places.length} mapped ${places.length===1?'place':'places'}. City and region pins locate the filming area; landmark pins identify a named place.`:esc(f.coverageNote||'A sourced filming location has not yet been mapped.')}</p>${places.map(l=>`<button class="film-place" data-film-location="${l.id}"><strong>${esc(l.name)}</strong><span>${esc(l.country)} · ${esc(l.scope)}</span></button>`).join('')}${places.length?`<button class="chip active" id="showFilmMap">Show on the globe</button>`:''}<p><a class="source-link" href="${esc(filmLink(f))}" target="_blank" rel="noopener">Film on IMDb ↗</a> · <a class="source-link" href="${esc(f.filmSource)}" target="_blank" rel="noopener">Film reference ↗</a></p></div>`;$('detail').showModal();$('detailBody').onclick=e=>{const b=e.target.closest('[data-film-location]');if(b){$('detail').close();openLocation(b.dataset.filmLocation)}};if(places.length)$('showFilmMap').onclick=()=>{$('detail').close();pivotFilm(id)}}
$('movieGrid').onclick=e=>{const b=e.target.closest('[data-film]');if(b)openFilm(b.dataset.film)};
document.addEventListener('click',e=>{const b=e.target.closest('[data-location]');if(b)openLocation(b.dataset.location)});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('detail').open&&!$('info').open){e.preventDefault();$('search').focus()}});
function openLocation(id){const l=LOCATIONS.find(x=>x.id===id);if(!l)return;selected=id;rotation=[-l.lon,-l.lat,0];drawGlobe();const p=photo(id);const fs=[...l.films].sort((a,b)=>Number(b.id===filmFilter)-Number(a.id===filmFilter)||a.year-b.year);$('detailBody').innerHTML=`${image(l).replace('loading="lazy"','class="detail-img"')}${p?`<div class="photo-credit">Photo: <a href="${p.sourcePage}" target="_blank" rel="noopener">${esc(p.creator)}</a> · <a href="${p.licenseUrl}" target="_blank" rel="noopener">${p.license}</a> · Display crop${l.id==='matera'?' · Wider Matera city view, not the exact square':''}</div>`:''}<div class="detail-content"><div class="eyebrow">${esc(l.tag)} · FILMING ${l.scope.toUpperCase()}</div><h2>${esc(l.name)}</h2><div class="location-line">${esc(l.city)} · ${esc(l.country)}</div><div class="gps"><code>${l.lat.toFixed(4)}°, ${l.lon.toFixed(4)}°</code><button id="copyGps">Copy GPS</button><a href="https://www.google.com/maps/search/?api=1&query=${l.lat},${l.lon}" target="_blank" rel="noopener">Open map ↗</a></div><p class="note">${esc(l.note)} Reference coordinates are approximate; they do not establish public access.</p>${fs.map(f=>`<article class="film-detail"><h3><a href="${filmLink(f)}" target="_blank" rel="noopener">${esc(f.title)} <span>${f.year} · IMDb ↗</span></a></h3><div class="small-label">${l.scope==='Landmark'?'THE SCENE':'THE FILMING CONNECTION'}</div><p>${esc(f.scene)}</p><div class="people">Director: ${person(f.director)}${f.cast.length?'<br>Cast: '+f.cast.map(person).join(' · '):''}</div><p><a class="source-link" href="${esc(f.source||l.source)}" target="_blank" rel="noopener">Filming reference ↗</a></p><button class="chip" data-pivot="${f.id}">Explore this film’s locations</button></article>`).join('')}<p class="note">Scene descriptions contain plot details. Location photographs show real places, not movie stills.</p></div>`;$('detail').showModal();$('copyGps').onclick=async()=>{try{await navigator.clipboard.writeText(`${l.lat}, ${l.lon}`);$('copyGps').textContent='Copied'}catch{$('copyGps').textContent='Select coordinates above'}};$('detailBody').onclick=e=>{const b=e.target.closest('[data-pivot]');if(b){$('detail').close();pivotFilm(b.dataset.pivot)}}}
for(const d of document.querySelectorAll('dialog')){d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})}
function info(credits=false){$('infoBody').innerHTML=`<div class="info-content"><div class="eyebrow">SCENE ATLAS</div><h2>${credits?'Sources & photo credits':'The world behind the screen'}</h2><p>${FILMS.length} films in ${collections.length} collections, with ${LOCATIONS.length} mapped places across ${new Set(LOCATIONS.map(l=>l.country)).size} countries and territories.</p><p>The catalog includes every released MCU feature through Spider-Man: Brand New Day (2026), major non-MCU Marvel films, the 25 Eon Bond films plus both non-series cinema films and the 1954 TV adaptation, all eight Mission: Impossible films, and the directed feature filmographies of Christopher Nolan, Steven Spielberg and George Lucas. Nolan’s available short films and documentary Quay are included too.</p><p>Other collections include Star Wars, Indiana Jones, Harry Potter and Fantastic Beasts, Middle-earth, Jurassic Park, Fast & Furious, John Wick, Bourne, Pirates of the Caribbean, Back to the Future, Terminator, Alien, Predator, Mad Max, Transformers, Batman & DC, Die Hard, Rocky & Creed, The Hunger Games, The Godfather, Ghostbusters, Men in Black, Planet of the Apes, Ocean’s, The Mummy, National Treasure, Narnia and Paddington.</p><p>Each film has a selected filming reference; this is not a list of every location used in each production. Landmark pins identify named sites. City and region pins identify a broader filming area and can include studio production. Coordinates are approximate reference points. Animated settings are not mapped as physical filming sites, and films without a confirmed place remain visible in Browse movies.</p><p>Collections overlap: a film may appear under its franchise and its director. Remakes are separated by title and release year. Director collections mean films directed by that person, with TV films and selected shorts labeled separately.</p>${credits?LOCATIONS.filter(l=>photo(l.id)).map(l=>{const p=photo(l.id);return `<div class="credit-entry"><strong>${esc(l.name)}</strong><br>Photo: <a href="${p.sourcePage}" target="_blank" rel="noopener">${esc(p.creator)}</a> · <a href="${p.licenseUrl}" target="_blank" rel="noopener">${p.license}</a> · Display crop<br><a href="${l.source}" target="_blank" rel="noopener">Filming location reference</a></div>`}).join(''):''}<p>Photographs are licensed as credited. New city and region cards show text and coordinates. No film posters or stills are reproduced. Film-specific filming sources appear in each location’s details.</p><p class="note">Globe boundaries: Natural Earth, public-domain geographical data. Map rendering: D3, ISC licence. This independent atlas is not affiliated with film studios or IMDb.</p></div>`;$('info').showModal()}
$('about').onclick=()=>info();$('credits').onclick=()=>info(true);
$('featured').innerHTML=['osterley','gorlitz','bradbury'].map(id=>{const l=LOCATIONS.find(x=>x.id===id);return `<button class="feature" data-location="${id}">${image(l)}<div><small>${esc(l.category.toUpperCase())} · ${esc(l.country.toUpperCase())}</small><h3>${esc(l.name)}</h3><p>${esc(l.films[0].title)}</p></div></button>`}).join('');
$('edition').textContent=`${FILMS.length} films · ${collections.length} collections · ${LOCATIONS.length} mapped places`;
let projection,geoPath;function drawGlobe(){if(!window.d3||!world)return;const svg=d3.select('#globe');svg.selectAll('*').remove();projection=d3.geoOrthographic().translate([325,270]).scale(238*zoom).rotate(rotation).clipAngle(90);geoPath=d3.geoPath(projection);const defs=svg.append('defs');const grad=defs.append('radialGradient').attr('id','ocean');grad.append('stop').attr('offset','0%').attr('stop-color','#253b42');grad.append('stop').attr('offset','100%').attr('stop-color','#182b32');svg.append('path').datum({type:'Sphere'}).attr('d',geoPath).attr('fill','url(#ocean)').attr('stroke','#607478').attr('stroke-width',1);svg.append('path').datum(d3.geoGraticule10()).attr('d',geoPath).attr('fill','none').attr('stroke','#47595e').attr('stroke-opacity',.32).attr('stroke-width',.65);svg.selectAll('.country-path').data(world.features).join('path').attr('class','country-path').attr('d',geoPath).attr('fill',d=>d.properties.name===country?'#708481':'#3d5459').attr('stroke','#23383e').attr('stroke-width',.7).on('click',(event,d)=>{if(d3.select('#globe').classed('dragging'))return;let c=d.properties.name;if(c==='USA'||c==='United States of America')c='United States';if(LOCATIONS.some(l=>l.country===c)){country=c;$('country').value=c;filmFilter='';render()}else{$('globeTitle').textContent=`${c} · no locations in this edition`}}).append('title').text(d=>d.properties.name);
const center=[-rotation[0],-rotation[1]];const visible=filtered().filter(l=>d3.geoDistance([l.lon,l.lat],center)<Math.PI/2);visible.forEach(l=>{const p=projection([l.lon,l.lat]);const g=svg.append('g').attr('class','map-pin').attr('transform',`translate(${p[0]},${p[1]})`).attr('role','button').attr('tabindex',0).attr('aria-label',l.name).on('click',()=>openLocation(l.id)).on('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLocation(l.id)}});g.append('circle').attr('r',11).attr('fill','transparent');g.append('circle').attr('r',l.id===selected?7:4.5).attr('fill','#efc17d').attr('stroke','#162830').attr('stroke-width',2);if(l.id===selected){g.append('circle').attr('r',13).attr('fill','none').attr('stroke','#efc17d').attr('opacity',.5);g.append('text').attr('class','pin-label').attr('x',17).attr('y',4).text(l.name)}g.append('title').text(l.name+' · '+l.films[0].title)});}
let dragStart=null,moved=false;const globe=$('globe');globe.addEventListener('pointerdown',e=>{if(e.target.closest('.map-pin'))return;dragStart={x:e.clientX,y:e.clientY,r:[...rotation]};moved=false});globe.addEventListener('pointermove',e=>{if(!dragStart)return;const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;if(Math.hypot(dx,dy)<4)return;moved=true;rotation=[dragStart.r[0]+dx*.35,Math.max(-85,Math.min(85,dragStart.r[1]-dy*.35)),0];drawGlobe();d3.select('#globe').classed('dragging',true)});window.addEventListener('pointerup',()=>{dragStart=null;setTimeout(()=>d3.select('#globe').classed('dragging',false),0)});globe.addEventListener('keydown',e=>{if(e.target!==globe)return;const keys={ArrowLeft:[-12,0],ArrowRight:[12,0],ArrowUp:[0,12],ArrowDown:[0,-12]};if(keys[e.key]){e.preventDefault();rotation[0]+=keys[e.key][0];rotation[1]=Math.max(-85,Math.min(85,rotation[1]+keys[e.key][1]));drawGlobe()}});$('zoomIn').onclick=()=>{zoom=Math.min(1.7,zoom+.15);drawGlobe()};$('zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.15);drawGlobe()};$('homeGlobe').onclick=()=>{rotation=[-12,-24,0];zoom=1;$('globeTitle').textContent='A world of cinema';drawGlobe()};
fetch('assets/world.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(w=>{world=w;drawGlobe()}).catch(()=>{$('globeTitle').textContent='Globe unavailable ,  explore the location list'});render();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'explore_film_locations',description:'Filter the atlas by a movie, place, actor or director and show matching real filming locations.',inputSchema:{type:'object',properties:{search:{type:'string'}},required:['search'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(typeof input?.search!=='string')throw Error('search must be a string');reset();query=input.search;$('search').value=query;setMode('globe');render();return filtered().map(l=>({id:l.id,name:l.name,country:l.country,latitude:l.lat,longitude:l.lon}))}})}catch{}}
